# Generated by Django 6.1 on 2026-09-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_position_name_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "LOW"),
                    ("medium", "MEDIUM"),
                    ("high", "HIGH"),
                    ("urgent", "URGENT"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="task.tasktype"
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="worker",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="task.position",
            ),
        ),
    ]
